"""Small LangSmith seam used by the walking-skeleton mock agent."""

from functools import lru_cache
from typing import Any

from langsmith import Client, traceable, tracing_context


@traceable(name="phase1-mock-agent", run_type="chain")
async def build_mock_answer(message: str) -> str:
    """Return a deterministic answer while creating the first traceable agent run."""

    return (
        "Phase 1 walking skeleton received your request: "
        f"{message} This response is generated by the temporary mock agent."
    )


@lru_cache(maxsize=4)
def get_langsmith_client(api_key: str, api_url: str) -> Client:
    """Return a shared client configured independently of process environment variables."""

    return Client(api_key=api_key, api_url=api_url)


async def run_traced_mock_agent(
    message: str,
    *,
    enabled: bool,
    api_key: str | None,
    project_name: str,
    metadata: dict[str, Any],
) -> str:
    """Trace when fully configured and otherwise execute without a network side effect."""

    tracing_enabled = enabled and bool(api_key)
    client = (
        get_langsmith_client(api_key, "https://api.smith.langchain.com")
        if tracing_enabled and api_key
        else None
    )
    with tracing_context(
        enabled=tracing_enabled,
        client=client,
        project_name=project_name,
        tags=["phase-1", "walking-skeleton"],
        metadata=metadata,
    ):
        return await build_mock_answer(message)
